### ISSUE TITLE
Upgrade to new future type

### ISSUE THREAD

**Issue by tdejager** [jonhoo/tokio-os-timer#10]
I wanted to use this in a project using a more recent version of tokio, and I could get it to work by using the futures compat layer. I think this is less than ideal.

I would like to take a shot a creating an std future compatible version, would you accept such a pull request? :)

**Comment by jonhoo** [comment]
Ah, I have actually intended to deprecate this crate in favor of [`async-timer`](https://github.com/DoumanAsh/async-timer/), which is a much more complete implementation (and it supports `std::future`). You may want to look at using that instead!

**Comment by tdejager** [comment]
Thanks!
