### ISSUE TITLE
Write a readme

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tokio-os-timer#8]
This should talk about:

 - Differences from `tokio-timer`
 - The different backend implementations
 - Timers in general ([`time(7)`](https://linux.die.net/man/7/time) is probably a good place to link to)
 - [`tokio-timerfd`](https://crates.io/crates/tokio-timerfd) which I just saw

**Comment by polachok** [comment]
I think having a platform-specific crate per OS would be a good idea, and a wrapper crate on top of them.
See also https://github.com/tokio-rs/tokio/pull/990#issuecomment-478734342

**Comment by jonhoo** [comment]
@polachok Ah, that's interesting.. I'm sort of inclined to keep them together in one crate, but with a `sys` implementation for each (much like `std` does), but having them ultimately end up in `tokio-timer` would be fantastic!
